### ISSUE TITLE
No Detected Staves

### ISSUE THREAD

**Issue by SilvainLouis** [zz85/nwc-viewer#2]
Hi,

I try to decode nwc file and I find your repo but I can't open a file, then I go to the debug window, I read "Detected Staves : 0".
Here is a exemple file : http://s000.tinyupload.com/index.php?file_id=85022586278908576132

Thanks

**Comment by zz85** [comment]
Hi @SilvainLouis, thanks for stopping by - it seems the attached uses the 1.55 format which I've never tested in the past. I should be able to add support for it sometime.
 
![image](https://user-images.githubusercontent.com/314997/80974561-be640d80-8dd5-11ea-934a-b218eafbfdfc.png)

**Comment by SilvainLouis** [comment]
Hi, Thanks for your reply. 
Can I help you to add support for this format ?

**Comment by zz85** [comment]
Hi @SilvainLouis - I've pushed some changes that allows some support for nwc 1.55. (You should be able to load up in http://zz85.github.io/nwc-viewer/ but currently still does not render the lyrics yet).

Let me know if you would like to make any improvements, I welcome contributions! :)

**Comment by zz85** [comment]
Since this file can now be loaded, I'll be closing this issue. Let me know if you come across other issues!

**Comment by SilvainLouis** [comment]
Hi Joshua,

Thanks for your work, I try a another file and the result is bumpy.
Here is somes files to test :
http://jemaf.free.fr/web/dalinker.php?file=jem1_nwc
I try the 002 and the 300 and I read only the D key.

A another file in (http://jemaf.free.fr/web/dalinker.php?file=jem4_nwc),
the number 1090, I read a lot of D and F key (in place of note)

A big big thank you for your work and don't hesitate if you want some help

Silvain




.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zz85** [comment]
Hi @SilvainLouis, version v2.3 is just released, please try again with https://zz85.github.io/nwc-viewer/ 

I think many of your nwc files should be better supported
